steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-proyecto-contables:$SHORT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/dev-proyecto-contables:$SHORT_SHA']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'dev-proyecto-contables', '--image=gcr.io/$PROJECT_ID/dev-proyecto-contables:$SHORT_SHA', '--region=us-east4', '--platform=managed']